In [30]:
# import library
# If you didn't install numpy before, you can install it using !pip install numpy
import numpy as np

In [31]:
# define a 2 by 2 array in numpy
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [32]:
# define a 2 by 2 matrix in numpy
b=np.matrix([[1,2],[3,4]])
b

matrix([[1, 2],
        [3, 4]])

In [33]:
# multiply two matrices by @
a@a


array([[ 7, 10],
       [15, 22]])

In [34]:
# Another approach to multyply two marices
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [35]:
# multiply two marices element by element
np.multiply(a,a)

array([[ 1,  4],
       [ 9, 16]])

In [36]:
# Product of all elements in a matrix
np.prod(a)

24

In [37]:
# Boardcasting with numpy
my_array=np.array([1,2,3])
my_array+5

array([6, 7, 8])

In [38]:
# define a 3 by 3 matrix by 1 elements  
c=np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
# Boardcasting with numpy
d=np.array([5,6,7])
c+d

array([[6., 7., 8.],
       [6., 7., 8.],
       [6., 7., 8.]])

In [40]:
# define a matrix by 1 elements 
g=np.ones((3,1))
g

array([[1.],
       [1.],
       [1.]])

In [41]:
# Boardcasting
n=np.array([5,6,7])
g+n

array([[6., 7., 8.],
       [6., 7., 8.],
       [6., 7., 8.]])

In [42]:
# sum function with numpy 
np.sum(a)

10

In [43]:
# cumsum function with numpy
np.cumsum(a , axis=1)

array([[1, 3],
       [3, 7]])

In [44]:
# subtruct with numpy
np.subtract(a,a)

array([[0, 0],
       [0, 0]])

In [45]:
# divide function with numpy
np.divide([5,6,7],3)

array([1.66666667, 2.        , 2.33333333])

In [46]:
# floor divide function with numpy
np.floor_divide([5,6,7],3)

array([1, 2, 2], dtype=int32)

In [47]:
# sqrt function with numpy
np.math.sqrt(5)

2.23606797749979

In [48]:
# nan variable
np.math.nan

nan

In [49]:
# inf variable with numpy
np.math.inf

inf

In [50]:
# generate random uniform numbers
np.random.uniform(1,5,(2,3))

array([[2.77838833, 4.74819461, 1.72519038],
       [4.18732392, 2.17473653, 4.51487718]])

In [51]:
# generate random number from standard normal distribution
np.random.standard_normal((2,1))

array([[-0.2640625 ],
       [-0.52785223]])

In [52]:
# arrange function with numpy
np.arange(1,10,3)

array([1, 4, 7])

In [53]:
# linspace function in numpy
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [54]:
# filter for dataset 
my_mask=a>2
a[my_mask]

array([3, 4])

In [55]:
# filter dataset by logical
my_mask2=np.logical_and(a>1,a<4)
a[my_mask2]

array([2, 3])

In [57]:
# zero array
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# call array a again
a

array([[1, 2],
       [3, 4]])

In [11]:
# size
np.size(a)

4

In [12]:
# shape
np.shape(a)

(2, 2)

In [29]:
# Some more functions with numpy
aa=np.array([1,2,3,4,1,3])
bb=np.array([7,8,9,1,3])
aa
bb

array([7, 8, 9, 1, 3])

In [16]:
# unique
np.unique(a)

array([1, 2, 3, 4])

In [17]:
# union
np.union1d(aa,bb)

array([1, 2, 3, 4, 7, 8, 9])

In [18]:
# intersection
np.intersect1d(aa,bb)

array([1, 3])

In [19]:
# mean
np.mean(aa)

2.3333333333333335

In [20]:
# median
np.median(aa)

2.5

In [21]:
# standard deviation of data
np.std(aa)

1.1055415967851334

In [22]:
# variance of data
np.var(aa)

1.2222222222222223

In [24]:
# define ploynomial x^2+2*x+2
mypoly=np.array([1,2,2])

In [26]:
# claculate polynomial at x=2
np.polyval(mypoly,2)

10

In [27]:
# derivative with numpy
np.polyder(mypoly)

array([2, 2])

In [28]:
# integral with numpy
np.polyint(mypoly)

array([0.33333333, 1.        , 2.        , 0.        ])